apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: foodgram
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kryssperer/foodgram-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /app/media/
            name: media
        envFrom:
        - configMapRef:
            name: db-configmap
        - secretRef:
            name: db-secret
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000