---
apiVersion: v1
kind: Namespace
metadata:
  name: foodgram

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: foodgram
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.0-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: postgres-data
        env: 
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: db-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: db-secret
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: SECRET_KEY
                name: db-secret
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: db-configmap
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: db-configmap
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: db-configmap
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                key: DEBUG
                name: db-configmap
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: foodgram
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: foodgram
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
