version: '3'

volumes:
  pg_data_production:
  static_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: baronfel/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: baronfel/taski_backend 
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: baronfel/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
    ports:
      - 9000:80