version: '3.7'

volumes:
  pg_data_kittygram:
  media:
  admin_static:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: kryssperer/kittygram_final-backend:1
    restart: always
    env_file: .env
    volumes:
      - admin_static:/backend_static
      - media:/app/media
    depends_on:
      - db
    
  gateway:
    image: kryssperer/kittygram_final-nginx:1
    restart: always
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - media:/media