version: '3'

volumes:
  pg_data_kittygram:
  kittygram_static:
  media:
  admin_static:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    restart: always
    env_file: .env
    volumes:
      - admin_static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - kittygram_static:/static
    command: cp -r /app/build/. /static/
    
  nginx:
    build: ./nginx/
    restart: always
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - kittygram_static:/static
      - media:/media
    depends_on: 
      - frontend
