apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-builder
  namespace: foodgram
spec:
  selector:
    matchLabels:
      app: frontend-builder
  template:
    metadata:
      labels:
        app: frontend-builder
    spec:
      containers:
      - name: frontend-builder
        image: kryssperer/foodgram-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /app/result_build/
            name: result-build
      volumes:
        - name: result-build
          persistentVolumeClaim:
            claimName: result-build-pvc