apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-builder
  namespace: foodgram
spec:
  selector:
    matchLabels:
      app: frontend-builder
  template:
    metadata:
      labels:
        app: frontend-builder
    spec:
      containers:
      - name: frontend-builder
        image: kryssperer/foodgram-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: result_build
  namespace: foodgram
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client